language: python

before_install:
 # https://code.google.com/p/gyp/wiki/GypHacking
 - git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
 - export PATH=$(pwd)/depot_tools:${PATH}
 - ninja --version

install:
 - python gyptest.py -a

before_script:
 - true

script:
 - true
